import { pgTable, text, serial, integer, timestamp, numeric, jsonb, boolean } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// --- Users ---
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull(), // 'contract_manager', 'reviewer', 'vendor'
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
});

// --- Vendors ---
export const vendors = pgTable("vendors", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  contactEmail: text("contact_email").notNull(),
  phone: text("phone"),
  address: text("address"),
  defaultRates: text("default_rates"),
  insuranceCertUrl: text("insurance_cert_url"),
});

// --- Contract Templates ---
export const contractTemplates = pgTable("contract_templates", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  defaultProjectName: text("default_project_name"),
  defaultBudgetAmount: numeric("default_budget_amount"),
  defaultDurationMonths: integer("default_duration_months"),
  baseContent: text("base_content"),
});

// --- Contracts ---
export const contracts = pgTable("contracts", {
  id: serial("id").primaryKey(),
  projectName: text("project_name").notNull(),
  projectNumber: text("project_number").notNull(),
  vendorId: integer("vendor_id").notNull(),
  templateId: integer("template_id"),
  startDate: timestamp("start_date").notNull(),
  endDate: timestamp("end_date").notNull(),
  budgetAmount: numeric("budget_amount").notNull(),
  status: text("status").notNull().default('draft'), // draft, in_review, approved, signed, executed
  documentContent: text("document_content"), // Full editable document
  aiAnalysis: jsonb("ai_analysis"), // AI findings, flagged clauses, scope alignment
  checklist: jsonb("checklist"), // Review checklist generated by AI
  createdAt: timestamp("created_at").defaultNow(),
});

// --- Notifications ---
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  contractId: integer("contract_id").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(), // 'approval_request', 'signing_request', 'status_update'
  read: boolean("read").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const contractSections = pgTable("contract_sections", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  status: text("status").notNull().default('pending'), // pending, approved, flagged
  assignedReviewerId: integer("assigned_reviewer_id"),
  comments: jsonb("comments"), // Array of comment objects
});

export const auditLogs = pgTable("audit_logs", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").notNull(),
  userId: integer("user_id").notNull(),
  action: text("action").notNull(), // "created", "section_approved", "status_changed"
  details: text("details"),
  createdAt: timestamp("created_at").defaultNow(),
});

// --- Base Schemas ---
export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export const insertVendorSchema = createInsertSchema(vendors).omit({ id: true });
export const insertContractTemplateSchema = createInsertSchema(contractTemplates).omit({ id: true });
export const insertContractSchema = createInsertSchema(contracts).omit({ id: true, createdAt: true, aiAnalysis: true, checklist: true, status: true, documentContent: true });
export const insertContractSectionSchema = createInsertSchema(contractSections).omit({ id: true });
export const insertAuditLogSchema = createInsertSchema(auditLogs).omit({ id: true, createdAt: true });
export const insertNotificationSchema = createInsertSchema(notifications).omit({ id: true, createdAt: true });

// --- Explicit API Contract Types ---
export type User = typeof users.$inferSelect;
export type Vendor = typeof vendors.$inferSelect;
export type ContractTemplate = typeof contractTemplates.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractSection = typeof contractSections.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type Notification = typeof notifications.$inferSelect;

export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertVendor = z.infer<typeof insertVendorSchema>;
export type InsertContractTemplate = z.infer<typeof insertContractTemplateSchema>;
export type InsertContract = z.infer<typeof insertContractSchema>;
export type InsertContractSection = z.infer<typeof insertContractSectionSchema>;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;

export type CreateContractRequest = InsertContract;
export type UpdateContractRequest = Partial<InsertContract> & { status?: string, documentContent?: string, aiAnalysis?: any, checklist?: any };
export type CreateVendorRequest = InsertVendor;
export type UpdateVendorRequest = Partial<InsertVendor>;
export type CreateSectionRequest = InsertContractSection;
export type UpdateSectionRequest = Partial<InsertContractSection>;
