import { pgTable, text, serial, integer, timestamp, numeric, jsonb, boolean } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// --- Users ---
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
});

// --- Vendors ---
export const vendors = pgTable("vendors", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  contactEmail: text("contact_email").notNull(),
  phone: text("phone"),
  address: text("address"),
  additionalInfo: text("additional_info"),
});

// --- Owners ---
export const owners = pgTable("owners", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  contactEmail: text("contact_email").notNull(),
  phone: text("phone"),
  address: text("address"),
  additionalInfo: text("additional_info"),
});

// --- Architects ---
export const architects = pgTable("architects", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  contactEmail: text("contact_email").notNull(),
  phone: text("phone"),
  address: text("address"),
  additionalInfo: text("additional_info"),
});

// --- Contract Templates ---
export const contractTemplates = pgTable("contract_templates", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  defaultProjectName: text("default_project_name"),
  defaultProjectLocation: text("default_project_location"),
  defaultBudgetAmount: numeric("default_budget_amount"),
  defaultDurationMonths: integer("default_duration_months"),
  baseContent: text("base_content"),
  docContent: text("doc_content"),                           // This will store the HTML template
  plainContent: text("plain_content"),                       // This will store the plain text content of the template
  template_file_path: text("template_file_path"),           // This will store the path to the template file in the supabase storage
  exhibits: jsonb("exhibits").default([]),
});

// --- Contracts ---
export const contracts = pgTable("contracts", {
  id: serial("id").primaryKey(),
  // Basic Project Info
  projectName: text("project_name").notNull(),
  projectLocation: text("project_location"),
  projectDescription: text("project_description"),
  projectNumber: text("project_number").notNull(),  
  // Owner Information
  ownerName: text("owner_name"),
  ownerStatus: text("owner_status"),
  ownerAddress: text("owner_address"),
  ownerInfo: text("owner_info"),
  // Architect Information
  architectName: text("architect_name"),
  architectStatus: text("architect_status"),
  architectAddress: text("architect_address"),
  architectInfo: text("architect_info"),
  // Vendor Information
  vendorId: integer("vendor_id").notNull(),
  vendorName: text("vendor_name"),
  vendorStatus: text("vendor_status"),
  vendorAddress: text("vendor_address"),
  vendorInfo: text("vendor_info"),
  // Project Details
  startDate: timestamp("start_date").notNull(),
  endDate: timestamp("end_date").notNull(),
  budgetAmount: numeric("budget_amount").notNull(),
  // Contract Details
  contractStartDate: timestamp("contract_start_date").notNull().defaultNow(),
  status: text("status").notNull().default('draft'),  // draft, review, approved, signed, executed
  lastActivityAt: timestamp("last_activity_at").notNull().defaultNow(), 
  // Content & Analysis
  documentContent: text("document_content"),          // Full editable document
  aiAnalysis: jsonb("ai_analysis"),                   // AI findings, flagged clauses, scope alignment
  checklist: jsonb("checklist"),                      // Review checklist generated by AI
  // Metadata
  createdAt: timestamp("created_at").defaultNow(),
  templateId: integer("template_id"),
  contract_docx_url: text("contract_docx_url"),       // This will store the URL of the generated DOCX file
  placeholder_data: jsonb("placeholder_data"),        // This will store the placeholder data for the contract
});

// --- Notifications ---
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  contractId: integer("contract_id").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(),                     // 'approval_request', 'signing_request', 'status_update'
  read: boolean("read").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const contractSections = pgTable("contract_sections", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  status: text("status").notNull().default('pending'),  // pending, approved, flagged
  assignedReviewerId: integer("assigned_reviewer_id"),
  comments: jsonb("comments"),                          // Array of comment objects
});

export const auditLogs = pgTable("audit_logs", {
  id: serial("id").primaryKey(),
  contractId: integer("contract_id").notNull(),
  userId: integer("user_id").notNull(),
  action: text("action").notNull(),                     // "created", "section_approved", "status_changed"
  details: text("details"),
  createdAt: timestamp("created_at").defaultNow(),
});

// --- Insert Schema for Contracts ---
export const insertContractSchema = createInsertSchema(contracts).omit({ 
  id: true, 
  createdAt: true, 
  aiAnalysis: true, 
  checklist: true, 
  status: true, 
  documentContent: true,
  contractStartDate: true,
  // vendorName: true,
  // vendorStatus: true,
  // vendorAddress: true,
  // vendorInfo: true
});

// --- Rest of the schemas ---
export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export const insertVendorSchema = createInsertSchema(vendors).omit({ id: true });
export const insertOwnerSchema = createInsertSchema(owners).omit({ id: true });
export const insertArchitectSchema = createInsertSchema(architects).omit({ id: true });
export const insertContractTemplateSchema = createInsertSchema(contractTemplates).omit({ id: true });
export const insertContractSectionSchema = createInsertSchema(contractSections).omit({ id: true });
export const insertAuditLogSchema = createInsertSchema(auditLogs).omit({ id: true, createdAt: true });
export const insertNotificationSchema = createInsertSchema(notifications).omit({ id: true, createdAt: true });

// --- Explicit API Contract Types ---
export type User = typeof users.$inferSelect;
export type Vendor = typeof vendors.$inferSelect;
export type Owner = typeof owners.$inferSelect;
export type Architect = typeof architects.$inferSelect;
export type ContractTemplate = typeof contractTemplates.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type ContractSection = typeof contractSections.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type Notification = typeof notifications.$inferSelect;

export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertVendor = z.infer<typeof insertVendorSchema>;
export type InsertOwner = z.infer<typeof insertOwnerSchema>;
export type InsertArchitect = z.infer<typeof insertArchitectSchema>;
export type InsertContractTemplate = z.infer<typeof insertContractTemplateSchema>;
export type InsertContract = z.infer<typeof insertContractSchema>;
export type InsertContractSection = z.infer<typeof insertContractSectionSchema>;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;

export type CreateContractRequest = InsertContract;
export type UpdateContractRequest = Partial<InsertContract> & { 
  status?: string, 
  documentContent?: string, 
  placeholderData?: Record<string, any>, 
  aiAnalysis?: any, 
  checklist?: any, 
  userId?: number,
  submittedByUserId?: number,
  assignedReviewerId?: number,
  returnedToAdminReason?: string,
  returnedToReviewerReason?: string
};
export type CreateVendorRequest = InsertVendor;
export type UpdateVendorRequest = Partial<InsertVendor>;
export type CreateSectionRequest = InsertContractSection;
export type UpdateSectionRequest = Partial<InsertContractSection>;
export type CreateOwnerRequest = InsertOwner;
export type UpdateOwnerRequest = Partial<InsertOwner>;
export type CreateArchitectRequest = InsertArchitect;
export type UpdateArchitectRequest = Partial<InsertArchitect>;